### ISSUE TITLE
Ability to permanently hide the pie chart

### ISSUE THREAD

**Issue by git2323** [RickZeeland/MaxiBug#1]
Hello,

I enjoy using this little helper. Thank you. I am not using the pie chart a lot, so it would be good, to permanently hide it, and just use it if requested.
I am using the version without a database (MiniBug v2).

Thanks

**Comment by RickZeeland** [comment]
Well, the original MiniBug does not have a pie chart and some of the extra features that MiniBug v2 has, would that be an option?

**Comment by RickZeeland** [comment]
Otherwise I could make it a setting under the "Misc" tab.

**Comment by git2323** [comment]
Yes, a setting for this would be much appreciated.
I am using this version:  https://github.com/RickZeeland/MiniBug-2

Thank you.

**Comment by RickZeeland** [comment]
Done! added a setting "Show Pie chart", uncheck this if you don't want to show the Pie chart on loading a project.

**Comment by git2323** [comment]
Works! I love it...
